version: '3.1'
services:
  updater:
    image: node:8
    working_dir: /app/src
    volumes:
    - ${MOUNT_SOURCE}/src:/app/src
    - ${MOUNT_SOURCE}/node_modules:/app/node_modules
    entrypoint: sleep
    command: '60000'
  db:
    image: pipelinedb/pipelinedb

